spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/h2-scheme/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace